config/routes.rb
EduStream1::Application.routes.draw do
 root  'static_pages#home'
 match '/signup',  to: 'users#new',            via: 'get'
 match '/about',   to: 'static_pages#about',   via: 'get'
 match '/contact', to: 'static_pages#contact', via: 'get'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def contact
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
 def full_title(page_title)
   base_title = "Ruby on Rails Tutorial Sample App"
   if page_title.empty?
     base_title
   else
     "#{base_title} | #{page_title}"
   end
 end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
 <small>
   <a href="http://edustre.am">Rails Tutorial</a>
   by Maxime Paul
 </small>
 <nav>
   <ul>
     <li><%= link_to "About",   about_path %></li>
     <li><%= link_to "Contact", contact_path %></li>
   </ul>
 </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
 <div class="navbar-inner">
   <div class="container">
     <%= link_to "eduStream_1", root_path, id: "logo" %>
     <nav>
       <ul class="nav pull-right">
         <li><%= link_to "Home",    root_path %></li>
         <li><%= link_to "Profile",    profile_path %></li>
         <li><%= link_to "Sign in", '#' %></li>
       </ul>
     </nav>
   </div>
 </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
<body>
    <%= render 'layouts/header' %>
<div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Us</h1>
<p>
  The <a href="http://edustre.am">eduStream App</a>
  is a project to re-invent education as a whole in a step-by-step process.
  This is the first phase release.  My name is Maxime Paul.  You can find 
  out more about me at <a href="http://maximepaul.com">my site</a>.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
<a href=http://maximepaul.com class="btn btn-primary btn-large"><i class="icon-white icon-envelope"></i> Link to the creator's website </a>
</p>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<h1>Home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>
<!--If signed in-->
<a href="#" class="btn btn-primary btn-large"><i class="icon-white icon-book"></i> Plan</a>
<a href="#" class="btn btn-primary btn-large"><i class="icon-white icon-film"></i> Stream</a>